services:
  app:
    container_name: nest-app
    env_file:
      - .env
    build: .
    ports: 
      - ${PORT}:${PORT}
    working_dir: /app
    volumes: 
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - net
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres-14
    build: ./database
    volumes: 
      - type: bind
        source: ./docker/postgres
        target: /src
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    networks:
      - net
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always

networks:
  net: